version: '3.3'
services:
  mongodb:
    image: "mvertes/alpine-mongo"
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27019:27017
    command: mongod --smallfiles --logpath=/dev/null
